source = colors.conf

### MONITORS ###
monitor = HDMI-A-2, 1920x1080@239.76, 0x0, 1


### MY PROGRAMS ###
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun


### AUTOSTART ###
exec-once = nm-applet
exec-once = waybar  
exec-once = awww-daemon
exec-once = swaync
exec-once = nvibrant 614 614 614
exec-once = sleep 1 && hyprctl setcursor Afterglow-cursors 24

### ENVIRONMENT VARIABLES ###
# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Afterglow-cursors
env = XCURSOR_PATH, /home/nrxg/.local/share/icons:/usr/share/icons:/usr/local/share/icons

env = GTK_THEME,Adwaita:dark
env = GTK_APPLICATION_PREFER_DARK_THEME,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_DATA_DIRS,$XDG_DATA_DIRS:/run/current-system/sw/share/gsettings-schemas/gsettings-desktop-schemas-47.1/share/gsettings-schemas

### PERMISSIONS ###
# See https://wiki.hyprland.org/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

source = ~/.config/hypr/configs/tags.conf
source = ~/.config/hypr/configs/looks.conf
source = ~/.config/hypr/configs/useranim.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/colors.conf

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]


### WINDOWRULES AND LAYERRULES
source = ~/.config/hypr/configs/windowrules.conf

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
    vfr = true # save resources
}

render {
	new_render_scheduling = true
}

### INPUT ###
source= ~/.config/hypr/configs/input.conf


### KEYBINDS ###
source= ~/.config/hypr/configs/keybinds.conf


